### ISSUE TITLE
add topic tags in About section

### ISSUE THREAD

**Issue by Beliavsky** [aradi/fytest#2]
I suggest adding topics such as `unit-test`, `unit-testing`, `test-framework`, `testing`, `test` in the About section

**Comment by aradi** [comment]
Thanks, that would be indeed a good idea in general. However, since I have deprecated this project in favor of [Fortuno](https://github.com/fortuno-repos/fortuno), I might be more happy, if people did not find Fytest at all :laughing: For [Fortuno](https://github.com/fortuno-repos/fortuno) I have added the topics you suggested here.
